# Generated by Django 5.1.6 on 2025-02-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VivaFit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='restricoes_alimentares',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
