# Generated by Django 5.1.6 on 2025-02-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VivaFit_app', '0002_alter_cliente_restricoes_alimentares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='restricoes_alimentares',
            field=models.TextField(blank=True, default='Nenhuma', null=True),
        ),
    ]
